language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t vjy0574/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true vjy0574/docker-react npm run test